'use client'

import { FormEvent, useEffect, useMemo, useState } from 'react'
import { ChevronDown, Cpu, FileCode2, Gauge, History, LayoutGrid, Library, MoreHorizontal, Paperclip, Plus, Radio, Search, Send, Settings2, Sparkles, Terminal, Trash2, Volume2, Wifi, X, Zap } from 'lucide-react'
import { retroApi, RetroMessage, RetroQueueItem, RetroSystem } from '../lib/retro-api'

const initialMessages: RetroMessage[] = [{ role: 'retro', text: 'Signal received. Give me a direction, problem, or strange idea and I will shape it into a system.', time: '09:41:14', tags: ['READY', 'LOCAL MODE'] }]
const history = ['Untitled session', 'Landing page / music AI', 'Brand voice sprint', 'Interface audit', 'Launch campaign']
const clock = () => new Date().toLocaleTimeString([], { hour12: false })

export function RetroWorkspace() {
  const [messages, setMessages] = useState(initialMessages)
  const [input, setInput] = useState('')
  const [context, setContext] = useState<number[] | null>(null)
  const [running, setRunning] = useState(false)
  const [mode, setMode] = useState('BUILD')
  const [rightOpen, setRightOpen] = useState(true)
  const [system, setSystem] = useState<RetroSystem>({ brightness: 78, volume: 62 })
  const [queue, setQueue] = useState<RetroQueueItem[]>([])
  const [error, setError] = useState('')

  useEffect(() => { Promise.all([retroApi.system(), retroApi.queue()]).then(([nextSystem, nextQueue]) => { setSystem(nextSystem); setQueue(nextQueue.items) }).catch(() => setError('Backend offline — local preview mode active.')) }, [])
  const hint = useMemo(() => mode === 'BUILD' ? 'Output is yours to direct' : mode === 'EXPLORE' ? 'Push into new territory' : 'Tune every detail', [mode])

  async function sendMessage(event: FormEvent) {
    event.preventDefault(); const text = input.trim(); if (!text || running) return
    setMessages(current => [...current, { role: 'user', text, time: clock() }]); setInput(''); setRunning(true); setError('')
    try { const data = await retroApi.chat(text, context); setContext(data.context); setMessages(current => [...current, { role: 'retro', text: data.reply || 'Signal received.', time: clock(), tags: ['GENERATED'] }]) }
    catch (caught) { setError(caught instanceof Error ? caught.message : 'Retro is offline.'); setMessages(current => [...current, { role: 'retro', text: 'Local mode is active. Your brief is queued and ready to shape into a new direction.', time: clock(), tags: ['LOCAL MODE'] }]) }
    finally { setRunning(false) }
  }
  async function adjust(key: 'brightness' | 'volume', value: number) { setSystem(current => ({ ...current, [key]: value })); try { await (key === 'brightness' ? retroApi.setBrightness(value) : retroApi.setVolume(value)) } catch { setError('Could not sync environment control.') } }
  async function addTask() { try { await retroApi.addQueue('New creative direction'); const next = await retroApi.queue(); setQueue(next.items) } catch { setError('Could not add queue item.') } }

  return <main className="app-shell">
    <aside className="side-rail"><div className="brand-mark"><span>R</span><div><strong>RETRO</strong><small>AI SYSTEM</small></div></div><button className="new-session" onClick={() => { setMessages([]); setContext(null) }}><Plus /> New session</button><div className="rail-label"><History /> Recent</div><nav className="history-list">{history.map((item, index) => <button className={index === 0 ? 'history-item active' : 'history-item'} key={item}><span className="history-dot" />{item}<MoreHorizontal /></button>)}</nav><div className="rail-bottom"><button><Library /> Library</button><button><Settings2 /> System settings</button><div className="user-chip"><div className="avatar">AM</div><span><b>Amish</b><small>Local operator</small></span><ChevronDown /></div></div></aside>
    <section className="workspace"><header className="topbar"><div className="crumb"><span className="pulse" /> RETRO / <b>WORKSPACE</b></div><div className="top-actions"><span className="status"><Wifi /> {error ? 'Offline fallback' : 'Local engine online'}</span><button className="icon-btn" aria-label="Search"><Search /></button><button className="icon-btn" aria-label="Toggle control room" onClick={() => setRightOpen(value => !value)}><LayoutGrid /></button></div></header><div className="canvas"><div className="canvas-heading"><div><p className="eyebrow">CREATIVE OPERATING SYSTEM <span>v2.4.0</span></p><h1>Make something<br /><em>unexpected.</em></h1></div><div className="run-state"><span className={running ? 'loader' : 'idle-dot'} /> {running ? 'PROCESSING SIGNAL' : 'READY TO GENERATE'}<small>LATENCY 24MS</small></div></div><div className="mode-row"><div className="mode-toggle">{['BUILD', 'EXPLORE', 'REFINE'].map(item => <button key={item} className={mode === item ? 'selected' : ''} onClick={() => setMode(item)}>{item}</button>)}</div><span className="mode-hint"><Zap /> {hint}</span></div>{error && <div className="notice" role="status">{error}</div>}<div className="conversation">{messages.length === 0 ? <div className="empty-state"><Sparkles /><p>Start with a direction, a problem, or a strange idea.</p></div> : messages.map((message, index) => <article className={message.role === 'user' ? 'message user-message' : 'message retro-message'} key={`${message.time}-${index}`}><div className="message-meta">{message.role === 'user' ? 'AM / YOU' : 'R / RETRO'}<span>{message.time}</span></div><p>{message.text}</p>{message.tags && <div className="tags">{message.tags.map(tag => <span key={tag}>{tag}</span>)}</div>}</article>)}</div><form className="composer" onSubmit={sendMessage}><div className="composer-top"><span className="prompt-symbol">›</span><input value={input} onChange={event => setInput(event.target.value)} placeholder="Tell Retro what you want to make..." aria-label="Prompt Retro" /><button type="button" className="attach" aria-label="Attach file"><Paperclip /></button></div><div className="composer-bottom"><span className="utility"><Terminal /> Context preserved</span><div className="composer-actions"><span>SHIFT + ENTER FOR NEW LINE</span><button className="send-button" disabled={running || !input.trim()}>{running ? <Radio className="spin" /> : <Send />} {running ? 'RUNNING' : 'GENERATE'}</button></div></div></form></div></section>
    {rightOpen && <aside className="inspector"><div className="inspector-head"><div><p className="eyebrow">LIVE SYSTEM</p><h2>Control room</h2></div><button className="icon-btn" aria-label="Close control room" onClick={() => setRightOpen(false)}><X /></button></div><div className="signal-card"><div className="signal-header"><span><Cpu /> RETRO CORE</span><span className="online">ONLINE</span></div><div className="signal-visual"><div className="orb"><span>R</span></div><div className="signal-copy"><b>{system.model ?? 'Creative mode'}</b><small>Adaptive reasoning active</small><div className="wave">{Array.from({ length: 10 }).map((_, i) => <i key={i} />)}</div></div></div></div><div className="inspector-section"><div className="section-title"><span>OUTPUT QUEUE</span><button aria-label="Add queue item" onClick={addTask}><Plus /></button></div>{queue.length ? queue.map((item, i) => <div className="queue-item" key={`${item.label}-${i}`}><span className="queue-status" /><div><b>{item.label}</b><small>{item.status ?? 'pending'}</small></div><span className="queue-time">{i ? 'NEXT' : 'NOW'}</span></div>) : <div className="queue-empty">No queued work.</div>}</div><div className="inspector-section controls"><div className="section-title"><span>ENVIRONMENT</span><Gauge /></div><label><span><Volume2 /> Volume</span><b>{system.volume}%</b><input type="range" value={system.volume} onChange={event => adjust('volume', Number(event.target.value))} /></label><label><span><Terminal /> Brightness</span><b>{system.brightness}%</b><input type="range" value={system.brightness} onChange={event => adjust('brightness', Number(event.target.value))} /></label></div><div className="inspector-footer"><button><FileCode2 /> View system log</button><button onClick={() => { setQueue([]); retroApi.clearQueue().catch(() => setError('Could not clear queue.')) }}><Trash2 /> Clear queue</button></div></aside>}
  </main>
}
